/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package franceinvaders;

import Framework.GamePanel;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.FloatControl;
import javax.sound.sampled.Mixer;
import javax.sound.sampled.Mixer.Info;
import javax.swing.DefaultListModel;

/**
 *
 * @author John
 */
public class Options extends javax.swing.JPanel {
    static Options menuOption;
    public static double master =   0.9;
    public static float defaultVolume = 70;
    public static float FxVolume = 70;
    public static float BgmVolume = 70;
    GamePanel previousScreen;
    
    private Options(GamePanel panel) {
        initComponents();
        previousScreen = panel;

        jSliderFx.setMaximum(80);
        jSliderFx.setMinimum(45);
        jSliderFx.setValue((int) defaultVolume);

        jSliderBgm.setMaximum(80);
        jSliderBgm.setMinimum(45);
        jSliderBgm.setValue((int) defaultVolume);

        jSliderMaster.setMinimum(0);
        jSliderMaster.setMaximum(100);
        jSliderMaster.setValue((int) (master*100));

        menuOption = this;
    }
    public static Options get(GamePanel panel){
        if (menuOption == null)
            return new Options(panel);
        else{
            menuOption.previousScreen = panel;
            return menuOption;
        }
            
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSliderBgm = new javax.swing.JSlider();
        jSliderFx = new javax.swing.JSlider();
        jSliderMaster = new javax.swing.JSlider();
        jButtonOK = new javax.swing.JButton();

        jSliderBgm.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderBgmStateChanged(evt);
            }
        });

        jSliderFx.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderFxStateChanged(evt);
            }
        });

        jSliderMaster.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderMasterStateChanged(evt);
            }
        });

        jButtonOK.setText("OK");
        jButtonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSliderBgm, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSliderFx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSliderMaster, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(jButtonOK)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSliderBgm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSliderFx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSliderMaster, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonOK)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jSliderFxStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderFxStateChanged
        FxVolume = jSliderFx.getValue();
        if (FxVolume == jSliderFx.getMinimum())
            FxVolume = -80;
    }//GEN-LAST:event_jSliderFxStateChanged

    private void jSliderMasterStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderMasterStateChanged
        double val = jSliderMaster.getValue();
        master = val/100;
    }//GEN-LAST:event_jSliderMasterStateChanged

    private void jSliderBgmStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderBgmStateChanged
       BgmVolume = jSliderBgm.getValue();
        if (BgmVolume == jSliderBgm.getMinimum())
            BgmVolume = -80;
    }//GEN-LAST:event_jSliderBgmStateChanged

    private void jButtonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOKActionPerformed
       previousScreen.getConteneur().remove(this);
       previousScreen.restaure();
    }//GEN-LAST:event_jButtonOKActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonOK;
    private javax.swing.JSlider jSliderBgm;
    public javax.swing.JSlider jSliderFx;
    private javax.swing.JSlider jSliderMaster;
    // End of variables declaration//GEN-END:variables
}
